source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'RWFramework_Example' do
  pod 'RWFramework', :path => '../'
end

target 'RWFramework_Tests' do
  pod 'RWFramework', :path => '../'
  #pod 'FBSnapshotTestCase'
  #pod 'Quick'
  #pod 'Nimble'
  #pod 'Nimble-Snapshots'
end


