source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'RWFramework_Example', :exclusive => true do
  pod 'RWFramework', :path => '../'
end

target 'RWFramework_Tests', :exclusive => true do
  pod 'RWFramework', :path => '../'

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
